### ISSUE TITLE
Training stopped before it even started. Please help to find out what is the reason?

### ISSUE THREAD

**Issue by Oliver0621** [qiuqiao/SOFA#24]
I have added the full_label, weak_label and no_label data normally. And binarize.py was successfully executed. The following is the result.
![image](https://github.com/qiuqiao/SOFA/assets/137243056/cfefd2a9-950a-4682-980c-babb80b8f656)

I have not modified the train_config.yaml configuration file.

I'm going to use a pretrained model for fine-tuning. The following result appeared, and then it paused. What is the problem?

![image](https://github.com/qiuqiao/SOFA/assets/137243056/16053de2-f688-4ba2-8a52-afc1f2254448)

**Comment by qiuqiao** [comment]
This looks like an error caused by missing data in the dataloader, in other words, there is too little data. In fact, SOFA currently does not recommend training with such a small amount of data, as it is very likely to cause overfitting. The next version of SOFA may support fine-tuning with a small amount of data before inference, but in the current version, we advise users to prepare sufficient data before training.

**Comment by Oliver0621** [comment]
OK, how long is the appropriate amount of data required? 30 minutes of audio in total? Or a total of 1 hour of audio?

**Comment by qiuqiao** [comment]
About 30 minutes.
